### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by StaticXNation** [Servius/tfa-sw-weapons-repository#12]
F11's are all error signs. Models are missing. http://prntscr.com/eyjki9

E11D has no sound when shooting

Imperial disruptor has a ton of Rex X's come out of it all around you when shooting. http://prntscr.com/eyjkcf

**Comment by Servius** [comment]
- [ ] Fix the F11s 
- [ ] Fix the E11D
- [ ] Fix the Imperial Disruptor

**Comment by Servius** [comment]
Going to switch the imperial disruptors tracer to something different for now. The l4d2 tracer is too high of a file size.
