### ISSUE TITLE
Expanded DC-15A syntax version bullet holes

### ISSUE THREAD

**Issue by gamerdude02** [Servius/tfa-sw-weapons-repository#13]
When I fire the DC-15A syntax version bullet holes show up on surfaces instead of laser blasts, this happens to the carbon version aswell

![20170429094349_1](https://cloud.githubusercontent.com/assets/28184407/25554251/7a7cd8fa-2cc0-11e7-9493-ba1b79622f7b.jpg)
![20170429094407_1](https://cloud.githubusercontent.com/assets/28184407/25554252/8442261a-2cc0-11e7-84ef-555afe63c667.jpg)

**Comment by Servius** [comment]
Okay. I believe i know what the issue is. Ill fix it in the morning. Currently have a map compiling.
