### ISSUE TITLE
TFA Flamethrower error

### ISSUE THREAD

**Issue by RamGilamar** [Servius/tfa-sw-weapons-repository#15]
[http://steamcommunity.com/sharedfiles/filedetails/?id=932486030](url)
that's what firing the flamethrower looks like in 1st person
BTW if the link doesn't work copy and past it into the search bar

**Comment by Servius** [comment]
Try downloading http://steamcommunity.com/sharedfiles/filedetails/?id=894273206

**Comment by RamGilamar** [comment]
perfect, thanks

**Comment by Servius** [comment]
Alright. Ill fix the issue for the standalone addon. I used the z6 rotary as the view so peeps be having problems because of that.
