### ISSUE TITLE
[TFA Reduxed] Star Wars Imperial Era Weapons Pack 1 & 2, problems

### ISSUE THREAD

**Issue by fuzzywhitebear** [Servius/tfa-sw-weapons-repository#17]
The packs we are using on the server are the [TFA Reduxed] Star Wars Imperial Era Weapons Packs 1 & 2 links below. On single player the guns work just fine however, bullets and shell casings come out from the sides of the weapons. There is also the issue where we on the server and are unable to spawn the TFA weapons, this maybe on our part and we are looking into. There is also the relbly v-10 mortar gun where when the gun is equipped it comes out of the player's abdomen. 

 Part 1 - http://steamcommunity.com/sharedfiles/filedetails/?id=887628821

Part 2 - http://steamcommunity.com/sharedfiles/filedetails/?id=887618739

TFA Base reduxed - http://steamcommunity.com/sharedfiles/filedetails/?id=415143062

**Comment by Servius** [comment]
Link me your server collection. Also, those weapon packs are not supported by me. 

http://steamcommunity.com/workshop/filedetails/?id=909236894
^These are supported by me. Extended pack has the same stuff.

**Comment by Servius** [comment]
@fuzzywhitebear

**Comment by Servius** [comment]
@fuzzywhitebear Hello?

**Comment by fuzzywhitebear** [comment]
I'm here sorry, I was not at the computer when you sent the messages, I
just got back. Thank you for sending me the link to that pack, I will be
sure to use those ones instead.

**Comment by Servius** [comment]
Alright. Ill consider this issue taken care of. Closing this now. @fuzzywhitebear
