### ISSUE TITLE
Scope Issue

### ISSUE THREAD

**Issue by AliciaStraymaus** [Servius/tfa-sw-weapons-repository#18]
For some reason, the 3D Scopes for the starwars weapons seem to show some random point on the map, rather then what I am looking at. Is there any reason for this? It really seems to only be your starwars weapons, and I believe I have all of the things needed for it.

Alternative question: All TFA weapons 3D scopes seem to turn white if I have GMDOOM enabled, including the starwars weapons, is there a reason for this as well?

**Comment by Servius** [comment]
Make sure you are using either my version of the tfa base or the tfa redux base. You cannot be using the sv base. 

Please link me whatever might explain what gmdoom is.

**Comment by Servius** [comment]
@AliciaStraymaus

**Comment by Servius** [comment]
No response nor was i able to replicate the issue. Closing.
