### ISSUE TITLE
Scope Not Working On Server!

### ISSUE THREAD

**Issue by FgCaboose** [Servius/tfa-sw-weapons-repository#19]
Hey so the scopes on a lot of your rifles in the TFA Starwars weapon pack have just PURE black scopes. Now I dont know why considering the following that we have downloaded all of your content and made sure it is all installed properly. Any ideas on this fix mate? That would be great!

**Comment by Servius** [comment]
Please link the following: 
Screenshot of the issue
Link to your server collection
Screenshot of your servers addons folder. 

I also need to know the following: 
Does it affect all players on the server? 
Is the bug present when playing in Singleplayer? 
Have you repackaged any of the tfa content into server content packs? 

@FgCaboose

**Comment by Servius** [comment]
No response nor was i able to replicate the issue. Closing.
