### ISSUE TITLE
Dont mean to be pushy, just curious. ETA on serverside disable of blaster lighting on walls?

### ISSUE THREAD

**Issue by Trebba** [Servius/tfa-sw-weapons-repository#20]
in the title, thats all :D

**Comment by Servius** [comment]
Currently clients can shut it off. The blaster effects have no effect on server performance meaning players with better computers should actually be able to handle the lighting. If you type "cl_dynamic_tracer 0"

**Comment by Servius** [comment]
@Trebba

**Comment by Trebba** [comment]
I cant see any of the scopes of the new CGI weapons like the t1,t5,t6,etc. I am on a SWRP server and we are using TFA Base SV, I downloaded your expanded weapons pack too

**Comment by Servius** [comment]
You absolutley cannot be using the sv base. Remove it and add the redux base.

**Comment by Trebba** [comment]
Ok so as a dev of the server, I should be only using the redux base for all TFA weapons? whats the point of the SV base then?

**Comment by Trebba** [comment]
because in the addon it says "darkrp is absolutely not supported"

**Comment by Servius** [comment]
Switch and the problems will no longer be there. 

When it says "not supported" it means tfa will not provide support for any server that is darkrp derived because most of the time there problems are self created.

**Comment by Servius** [comment]
@Trebba

**Comment by Servius** [comment]
No response. Assuming solved.
