### ISSUE TITLE
Not able to see down scopes?

### ISSUE THREAD

**Issue by Trop1cal** [Servius/tfa-sw-weapons-repository#24]
Hello! I'm currently having issues seeing down the scopes of weapons in the TFA packs, even though I already have all the resources, and currently just reinstalled them, I have every single source game except L4D, and L4D2. Any help? Thanks.

**Comment by Servius** [comment]
Alright. @Trop1cal Please send me a screenshot of the issue. 

Also, please do/answer the following: 

- Delete all .gma files in the garrysmod/garrysmod/addons folder. 
- Make sure all related addons are enabled via the GMod Main Menu -> Addons menu. 
- If problem is still present try unsubscribing from other addons. There is a list of incompatible addons in the Offical TFA group. Check that for the incompatible addons.
