### ISSUE TITLE
TFA Expanded Weapons Pack Error 

### ISSUE THREAD

**Issue by unknownarkon** [Servius/tfa-sw-weapons-repository#28]
Basically i have the Expanded weapons pack(With the required addons) and no weapons have sound some dont have viewmodels and some are errors any help ?

![image](https://user-images.githubusercontent.com/26172512/33216245-f24364b2-d12a-11e7-9b00-a8ce8732b2b8.png)

![image](https://user-images.githubusercontent.com/26172512/33216249-fd063ece-d12a-11e7-8132-6179c213284d.png)

**Comment by Servius** [comment]
#34
