### ISSUE TITLE
Missing sounds and lots of ERRORs

### ISSUE THREAD

**Issue by DavidPires7** [Servius/tfa-sw-weapons-repository#31]
I have all the weapons from the "Compatible Weapons Pack" of Star Wars weapons, and most of the guns are ERRORs, there aren't icons in the Spawn Menu and none of them have sounds. I have tried reinstalling GMOD and deleting the addons folder twice and redownloading all. I've also checked for addons that could have compatibility issues and found nothing. I don't know if this is related but some of my basic HL2 weapons, like the crossbow, have viewmodel issues (there are a bunch of black lines floating all around the crossbow, like if there were polygons cut by the player's view camera).

Also, other users with the same content pack as me don't have these issues.

Thanks for any help you can provide

**Comment by Servius** [comment]
@DavidPires7 Make sure the addons are enabled via the addons menu. If that doesnt check out then take a look at the server collection(if this is being tested on a server)
