### ISSUE TITLE
All guns are missing pictures

### ISSUE THREAD

**Issue by jgillis14** [Servius/tfa-sw-weapons-repository#34]
Hello,

I have recently added your workshop to my server and all of the guns images do not show.  

I have supplied a picture of what I mean by "images do not show."
https://gyazo.com/778bec7f47c3e8f08018a1f2ea30642e

**Comment by ahnok** [comment]
Have you included the shared resources addon which is required for most TFA star ware weapons? Both the sounds and images should be included there.

Von meinem iPhone gesendet

**Comment by Servius** [comment]
@jgillis14 Please make sure that the shared addon is on your server collection.
