### ISSUE TITLE
errors when players shoot 

### ISSUE THREAD

**Issue by Chinfu1189** [Servius/tfa-sw-weapons-repository#36]
So this started to happen this week not sure why cause i havent subbed to any new addons and the server i play on hasnt changed anything 
So what happens when any player is using a TFA weapon a error appears and dissapear everytime there shooting or each blaster bolt flys out i tryed deleteing the GMA file resubbing to the Addons still errors and im not sure how to fix it 
Also in single player im getting errors saying there two of the same addon of what the console says 
File exists in two addons - possible conflicts! lua/ulib/shared/hook.lua (ULib and TFA Base)

[TFA Base] lua/tfa/modules/tfa_rtbgblur.lua:55: attempt to call method 'GetStat' (a nil value)
  1. v - lua/tfa/modules/tfa_rtbgblur.lua:55
   2. unknown - lua/includes/modules/hook.lua:84

**Comment by Servius** [comment]
https://github.com/Servius/tfa_base_rp_friendly

**Comment by Servius** [comment]
#37
