### ISSUE TITLE
Errors on firing some of the weapons

### ISSUE THREAD

**Issue by StaticGamerz** [Servius/tfa-sw-weapons-repository#37]
So I run a server and I use TFA weapons. On all of the dual pistols, Republic sniper, CIS and Republic shotgun and the explosive version of the bowcaster there seems to be a problem. If any of these weapons are fired what I presume to be the empty casing appear as errors. These errors appear right in front of the player and make the weapon unusable. I have tried re-installing the addons and nothing has changed. I have also made sure that all the required addons are installed on the server but nothing has changed. I will be really grateful if you could get back to me or publish a small announcement of the addon page on the issue as I have seen others have this issue as well.

**Comment by Servius** [comment]
https://github.com/Servius/tfa_base_rp_friendly

**Comment by Servius** [comment]
Have your server switch from the workshop tfa base to this.
