### ISSUE TITLE
E-11 Scope is messed up

### ISSUE THREAD

**Issue by Garrus167** [Servius/tfa-sw-weapons-repository#64]
**Describe the bug**
Honestly just look at the screenshot. I can't explain it. I've been seeing if I can come up with a fix myself, but I have no idea what to do for this.

**Screenshots**
https://steamcommunity.com/sharedfiles/filedetails/?id=1662043432

**Comment by DT066** [comment]
I have the exact same problem, hoping for a fix.

**Comment by Servius** [comment]
@Garrus167 @DT066 Switch scope quality to medium in TFA settings.
