### ISSUE TITLE
All of the weapons glitch out quite literally.

### ISSUE THREAD

**Issue by viesta2015** [Servius/tfa-sw-weapons-repository#70]
![image](https://user-images.githubusercontent.com/5360790/62430430-3f289880-b6e2-11e9-9f84-a9c9789aa488.png)
don't know what to do with this... im just trying to help a community out

**Comment by Servius** [comment]
Ill assume this was during the download issues. Otherwise make sure the shared resources addon has been downloaded and is enabled.
