### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by KuhakuORIGIN** [Servius/tfa-sw-weapons-repository#74]
**Describe the bug**
Whenever I shoot some of the weapons, it results in an error and if I do it too much it crashes my game. 

**To Reproduce**
1. Go to the Q menu.
2. Click on "Weapons".
3. Scroll down to "TFA Star Wars: Deathwatch" and click on it.
4. Equip the "Deathwatch Wrist Blaster" (Most left weapon.)
5. Start blasting.

**Expected behavior**
The gun would shoot and display no errors.

**Screenshots**
![errorsad](https://user-images.githubusercontent.com/59211787/71426157-021b6d80-26a6-11ea-989b-f247722bc245.png)

**Desktop (please complete the following information):**
 - Windows 8.1

**Additional context**
In this I will only show ONE of the weapons as I do not know all of the weapons that do it.

**Comment by Servius** [comment]
This was posted during a widespread issue with TFA and the workshop itself. The error itself has since been solved. @KuhakuORIGIN
