### ISSUE TITLE
[BUG] TFA Star Wars Extended

### ISSUE THREAD

**Issue by Zen3DMA** [Servius/tfa-sw-weapons-repository#75]
**Describe the bug**
The republic launcher in TFA Star Wars Weapons Extended is acting as a sniper rifle and is not reproducing any rocket launcher attributes.

**To Reproduce**
Simply Spawn in the Republic Launcher from the Q-Menu in Gmod, and It seems to replicate itself as a Sniper Rifle, on a live server.

If you spawn it on Singleplayer it does deploy a rocket, yet it's catergoy is still completely wrong.

**Expected behavior**
To act as a Rocket Launcher and Deploy a Rocket Launcher Rocket.

**Screenshots**
Multiplayer:
![image](https://user-images.githubusercontent.com/35611537/74293357-74b5da80-4d32-11ea-8714-2d3be69a46e3.png)

Singleplayer:
![image](https://user-images.githubusercontent.com/35611537/74293582-2b19bf80-4d33-11ea-8f87-5f9e945db253.png)

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by Servius** [comment]
There isnt a republic launcher in the extended pack.

**Comment by Zen3DMA** [comment]
https://github.com/Servius/tfa-sw-weapons-repository/blob/master/Live%20Addons/servius_uploader/tfa_swrp_expanded_weapons_pack/lua/weapons/tfa_swch_clonelauncher_3/shared.lua

**Comment by Zen3DMA** [comment]
Seems there is.

**Comment by Servius** [comment]
Thats the Expanded pack, not the extended pack.

**Comment by Servius** [comment]
@Zen3DMA
