### ISSUE TITLE
Expanded Pack 

### ISSUE THREAD

**Issue by Servius** [Servius/tfa-sw-weapons-repository#9]
- Move all non-scoped weapons to tfa_gun_base
- Remove all unneeded dependencies ie tfa_swsft_base
- Make changelog print to player as well. 
    - Make changelog check if outdated (see wand addon)

**Comment by DovaDopler** [comment]
Hey, i been having a issue lately with one of your addons, which is the DC-15A Scoped. The problem is the scope is an error for me while the rest of the gun is fine. If there any way to fix it, it would be appreciated.

https://gyazo.com/fc453e61124aace8aae174bb121a2758
